### PR TITLE
Remove FUNDING.yml

### PR DESCRIPTION
**Pull request by gary-kim**
I am no longer the primary maintainer so it doesn't
really make sense to have the FUNDING.yml point to
my pages.

Signed-off-by: Gary Kim <gary@garykim.dev>

### CODE REVIEW

**Comment by Suhas-13** [comment]
> I am no longer the primary maintainer so it doesn't
> really make sense to have the FUNDING.yml point to
> my pages.
> 
> Signed-off-by: Gary Kim [gary@garykim.dev](mailto:gary@garykim.dev)

It's up to you, but considering you wrote most of this, I think it would still make sense to keep that in place.

**Review by Suhas-13 — APPROVED** [review]

**Comment by gary-kim** [comment]
I can't really receive donations right now anyways so let's get rid of it :)

**Comment by Suhas-13** [comment]
> I can't really receive donations right now anyways so let's get rid of it :)

Sure, I guess it makes sense to remove if that's the case.

**Comment by Suhas-13** [comment]
It seems like Travis CI isn't resolving for some reason. Not sure why that is.

**Comment by gary-kim** [comment]
Huh. Let me try bumping it

**Comment by gary-kim** [comment]
Oh, we ran into Travis CI's new limits. Let me make a PR to switch to either GitHub Actions or Drone CI.

**Comment by Suhas-13** [comment]
Maybe bump this @gary-kim?

**Pull request merged**
