### PR TITLE
removed analytics code, as it is not being used, modified extension options page

### PR DESCRIPTION
**Pull request by Suhas-13**
removed analytics code throughout the extension as it was not being used, also modified the extension options page to include a link to GitHub issues and a contact email for bugs/inquiries.
Signed-off-by: Suhas Hariharan <hariharan774531@sas.edu.sg>

### CODE REVIEW

**Review by gary-kim — APPROVED** [review]
LGTM

**Comment by gary-kim** [comment]
Do need to fix the linter issues, though

**Comment by Suhas-13** [comment]
> Do need to fix the linter issues, though

just fixed it, sorry, didn't see it earlier.

**Comment by Suhas-13** [comment]
closes #233

**Pull request merged**
