### PR TITLE
Fix options page and remove extension info option

### PR DESCRIPTION
**Pull request by Suhas-13**
Fix options page and remove extension info option

### CODE REVIEW

**Review by priime0 — APPROVED** [review]
lgtm :+1:

**Comment by gary-kim** [comment]
Oh, what was the removal of the extension info option for?

**Comment by Suhas-13** [comment]
I just realised it wasn't an option in the extension option page so I thought I'd just remove it for now, if you'd prefer I can add it back and make it a proper selectable option in the page.

**Comment by gary-kim** [comment]
It's used to control whether or not the extension info page is open or closed: https://github.com/sas-fossdev/saspes/blob/f48f55afffb39f611ed174f756d8112680fbdf74/src/js/components/ExtensionInfo.vue#L87-L90

**Comment by Suhas-13** [comment]
ah, sorry I completely missed that functionality, I assumed it was yet to be implemented on the options page. I can re-add that in another PR.

**Comment by Suhas-13** [comment]
closes #239

**Pull request merged**
